# Generated by Django 5.2.5 on 2025-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('disability', models.BooleanField(default=False)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('id_upload_front', models.FileField(upload_to='uploads/ids/front/')),
                ('id_upload_back', models.FileField(upload_to='uploads/ids/back/')),
                ('phone_number', models.CharField(max_length=15)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_id', models.CharField(max_length=50)),
                ('ward', models.CharField(choices=[('kivaa', 'Kivaa'), ('masinga-central', 'Masinga Central'), ('ndithini', 'Ndithini'), ('ekalakala', 'Ekalakala'), ('muthesya', 'Muthesya')], max_length=50)),
                ('village', models.CharField(max_length=100)),
                ('chief_name', models.CharField(max_length=255)),
                ('chief_phone', models.CharField(max_length=15)),
                ('sub_chief_name', models.CharField(max_length=255)),
                ('sub_chief_phone', models.CharField(max_length=15)),
                ('level_of_study', models.CharField(choices=[('degree', 'Degree'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('artisan', 'Artisan')], max_length=20)),
                ('institution_type', models.CharField(choices=[('college', 'College'), ('university', 'University')], max_length=20)),
                ('institution_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('mode_of_study', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=20)),
                ('year_of_study', models.CharField(choices=[('first-year', 'First Year'), ('second-year', 'Second Year'), ('third-year', 'Third Year'), ('final-year', 'Final Year')], max_length=20)),
                ('admission_letter', models.FileField(upload_to='uploads/admission_letters/')),
                ('family_status', models.CharField(choices=[('both-parents-alive', 'Both Parents Alive'), ('single-parent', 'Single Parent'), ('partial-orphan', 'Partial Orphan'), ('total-orphan', 'Total Orphan')], max_length=50)),
                ('father_death_certificate', models.FileField(blank=True, null=True, upload_to='uploads/death_certificates/')),
                ('mother_death_certificate', models.FileField(blank=True, null=True, upload_to='uploads/death_certificates/')),
                ('father_income', models.CharField(blank=True, choices=[('low', 'Low (Below KSh 20,000/month)'), ('medium', 'Medium (KSh 20,000 - 50,000/month)'), ('high', 'High (Above KSh 50,000/month)')], max_length=20, null=True)),
                ('mother_income', models.CharField(blank=True, choices=[('low', 'Low (Below KSh 20,000/month)'), ('medium', 'Medium (KSh 20,000 - 50,000/month)'), ('high', 'High (Above KSh 50,000/month)')], max_length=20, null=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
