# Generated by Django 5.2.5 on 2025-10-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplication',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
