# Generated by Django 5.2.5 on 2025-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_alter_bursaryapplication_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplication',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/admission_letters/'),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='id_upload_back',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ids/back/'),
        ),
    ]
