# Generated by Django 5.2.5 on 2025-10-07 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_alter_bursaryapplication_admission_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bursaryapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Bursary Application', 'verbose_name_plural': 'Bursary Applications'},
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators', null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='approved_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='disability_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='fee_structure',
            field=models.FileField(blank=True, null=True, upload_to='uploads/fee_structures/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
