# Generated by Django 5.2.5 on 2025-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0004_alter_bursaryapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bursaryapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='disability_details',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='bursaryapplication',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
