# Generated by Django 5.2.5 on 2025-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0005_alter_bursaryapplication_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['reference_number'], name='bursary_bur_referen_59789d_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['ward'], name='bursary_bur_ward_43f971_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['submitted_at'], name='bursary_bur_submitt_613d48_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['status'], name='bursary_bur_status_cb41a2_idx'),
        ),
    ]
