# Generated by Django 5.2.5 on 2025-10-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0007_add_audit_and_deadline_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
