# Generated by Django 5.2.5 on 2025-12-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0010_make_id_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='applicant_photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/applicant_photos/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_letter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/chief_letters/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='communication_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='deceased_single_parent_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/death_certificates/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='disability_proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/disability_proof/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='orphan_sibling_proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orphan_proof/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='residency_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='single_parent_proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/single_parent_proof/'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='uploads/transcripts/'),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='father_income',
            field=models.CharField(blank=True, choices=[('low', 'Low (KSh 1,000 – 10,000)'), ('medium', 'Medium (KSh 10,001 – 30,000)'), ('high', 'High (KSh 30,001 – 50,000)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='mother_income',
            field=models.CharField(blank=True, choices=[('low', 'Low (KSh 1,000 – 10,000)'), ('medium', 'Medium (KSh 10,001 – 30,000)'), ('high', 'High (KSh 30,001 – 50,000)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='year_of_study',
            field=models.CharField(choices=[('first-year', 'First Year'), ('second-year', 'Second Year'), ('third-year', 'Third Year'), ('fourth-year', 'Fourth Year'), ('fifth-year', 'Fifth Year'), ('sixth-year', 'Sixth Year'), ('seventh-year', 'Seventh Year')], max_length=20),
        ),
    ]
