# Generated by Django 5.2.5 on 2025-12-05 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0011_bursaryapplication_applicant_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bursaryapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name_plural': 'Bursary Applications'},
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='institution_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='applicationstatuslog',
            index=models.Index(fields=['application', '-changed_at'], name='bursary_app_applica_7b8a34_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatuslog',
            index=models.Index(fields=['-changed_at'], name='bursary_app_changed_af3e73_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['email'], name='bursary_bur_email_8b609e_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['id_number'], name='bursary_bur_id_numb_4e42d4_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['phone_number'], name='bursary_bur_phone_n_85b8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['full_name'], name='bursary_bur_full_na_bc8ece_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['institution_name'], name='bursary_bur_institu_340d51_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='bursary_bur_status_c56857_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['ward', 'status'], name='bursary_bur_ward_05302d_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['year_of_study', 'status'], name='bursary_bur_year_of_d22ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['family_status', 'status'], name='bursary_bur_family__21020a_idx'),
        ),
    ]
